### ISSUE TITLE
Connections page shows 404

### ISSUE THREAD

**Issue by crai9** [DevWars/devwars-web#1]
While logged in [https://www.devwars.tv/settings/connections](https://www.devwars.tv/settings/connections) shows:

404
Page not found
The page you are looking for does not exist. Sorry!

![xgott3v](https://user-images.githubusercontent.com/8229723/36937487-d92c60bc-1f0b-11e8-83cd-e2086da170f1.png)

**Comment by mongui** [comment]
Here: https://www.devwars.tv/games

It also happens when clicking on the buttons "View game code" and "View Blue/Red website".
