### ISSUE TITLE
Blog dates are off

### ISSUE THREAD

**Issue by Freakspot** [DevWars/devwars-web#3]
The dates in blog entries are off by.. years I think.

![image](https://i.imgur.com/HEtcYbY.png)
![image](https://user-images.githubusercontent.com/2371427/43992122-173f3716-9d7a-11e8-80d5-e58b5e066590.png)

**Comment by ChrisRu** [comment]
https://github.com/DevWars/devwars.tv/blob/f6c3be670b548daaa0add63a64aaf2ba314d080d/components/blog/BlogCard.vue#L8 seems like those are just static :)

**Comment by Freakspot** [comment]
Wow, I hadn't even realized they were all the same.
I'm curious what's up with the upper one tho? That was taken from a specific entry. @ChrisRu
