### ISSUE TITLE
Lots of missing fav icons that need changing:

### ISSUE THREAD

**Issue by stephen-slm** [DevWars/devwars-web#63]
- [ ] Moderation Panels

**Comment by stephen-slm** [comment]
@SYNTAG It looks like there was a lot of older fa stuff since moving away from the paid version, i'm not sure directly how it was build or made but could this be something you could resolve?  since its broken all the icons.

**Comment by syntag** [comment]
@MambaDev I can't seem to replicate the fonts not showing up. I thought maybe it was because my computer had the fonts installed locally. But I tried logging on to several computers/phones that never went to DevWars before and was able to see the icons.

**Comment by stephen-slm** [comment]
Its not related to fonts but fontAwesome icons. @SYNTAG 

![image](https://user-images.githubusercontent.com/12329422/78424515-163c1700-7666-11ea-905f-20cbbabec486.png)

You can see it here with the icons next to the headers of the table.

**Comment by stephen-slm** [comment]
@SYNTAG its also on the core site.

![image](https://user-images.githubusercontent.com/12329422/78424568-7337cd00-7666-11ea-8941-36537acc2f2f.png)

**Comment by syntag** [comment]
@MambaDev Yes, I was referring to FontAwesome icons as a font. Strange how I am able to see the font on multiple devices. I'll try to look into it again and circle back on this one.

**Comment by stephen-slm** [comment]
@SYNTAG just to add, they don't render at all on Edge (just seems to render broken on chrome?)
