### ISSUE TITLE
Don't show the live game in the games panel or display it as LIVE since it is completely empty otherwise.

### ISSUE THREAD

**Issue by stephen-slm** [DevWars/devwars-web#67]

**Comment by stephen-slm** [comment]
It looks like @samdharris is going to have a look at this and see if they can resolve it as a good starting point to be more involved in the project.

**Comment by samdharris** [comment]
@MambaDev I'm considering making the API do this. Even though I've done it on the front-end, it makes more sense for the API to return that data?

**Comment by stephen-slm** [comment]
@samdharris The api is going to return all games, active or not. Since these could be used else where, e.g updating the section of the home page to show live game status and results. 

Just as a note, if you feel a change would be a 'business' change, start by opening a issue that could result in a discussion. When its more than just a fix.
